- application/events/helpers.py
- application/events/tests/test_helpers.py
-Fixed issue when adding a month to an event on the 31st of a month
-Added tests
-fixes #177
> Fixed event adding month issue

- application/events/helpers.py
- application/events/tests/test_api.py
- application/events/tests/test_helpers.py
- application/events/urls.py
- application/events/views.py
-Refactored event helper functions to get repeated events
-Added more tests for event helper functions
-Removed json view that is no longer used
> Fixed errors with event calendar

- application/accounts/models.py
- application/accounts/tests/test_password_reset.py
- application/accounts/urls.py
- application/accounts/views.py
* Write API method to reset passwords
* Added url on `api/account/password-reset`
* Tests
Closes #193
> Password Reset API

- README.md
codeship status url needed to be updated because the repo url changed
> Update Readme - codeship status

- README.md
- application/dataentry/tests/test_csv_exporter.py
- application/dataentry/tests/tests.py
- application/dataentry/urls.py
- application/dataentry/views/__init__.py
- application/dataentry/views/all_views.py
- application/dataentry/views/csv_exporter.py
- application/export_import/__init__.py
- application/rest_api/urls.py
The source of the problem was that google_sheets was not being imported and so the event handlers were never
registered for the irf_done and vif_done signals.  Added an import of google_sheets in the __init__ under
export_import to make sure the registration occurs.
I believe that google_sheets was being imported in the views. However,  since it was not really needed there,
the import was removed as part of the cleanup.
> Fix issue with data not being exported to Google Sheets.

- build/nginx/Dockerfile
Set nginx run.sh as executable
> Fix for running on Docker for Windows

- application/static_border_stations/tests/test_border_station_api.py
- application/static_border_stations/views.py
-Also added tests
connects to #230
> Added filtering capability to Border Stations API

- application/budget/models.py
- application/budget/tests/test_budget.py
Added support for adding extra items for the admin and medical budget categories. Also modified tests accordingly
> extra items for admin / medical budget categories

- application/dataentry/tests/test_irfvif_exists_views.py
- application/dataentry/urls.py
connects to #196 
When I added the ability to have letters in the url after the number, I accidentally made that a requirement. This PR changes the suffix letters to optional and I wrote a couple tests to verify
> Save for Later Fix

- application/dataentry/serializers.py
- application/portal/tests/test_views.py
- application/portal/views.py
> add YTD serialized field to borderstations

- application/budget/views/budget_views.py
We should still pull in intercepts data for previous months even if we do not have any previous budget sheets.
Connects to #215
> We were previously not getting interception data if there were no Budget Sheets

- docker-compose.yml
This will allow us to more easily debug django stuff
I wrote up some documentation for it [here](https://github.com/Tiny-Hands/tinyhands/wiki/Interactive-Debugging-Django-inside-Docker)
> adding stdin and tty support to the web container

- application/dataentry/serializers.py
- application/dataentry/views/__init__.py
- application/dataentry/views/country.py
- application/rest_api/urls.py
connects to Tiny-Hands/tinyhands-client#133
> Added backend support for country management page

- docker-compose.yml
> update the docker-compose file

- application/budget/views/budget_views.py
- docker-compose.yml
fixing 500 error on top table data call
> Deploy to Production

- application/dreamsuite/settings/base.py
- application/dreamsuite/settings/local.py
- application/dreamsuite/settings/production.py
- application/dreamsuite/settings/staging.py
- application/dreamsuite/settings/testing.py
- codeship-services.yml
- common.env
> moving site_domain and client_domain into environment variables

- application/dataentry/serializers.py
Added Locations to the Border Station Serializer
connects to #283
> Added Locations to the Border Station Serializer

- application/budget/helpers.py
- application/budget/models.py
- application/budget/pdfexports/mdf_exports.py
- application/budget/pdfexports/pdf_creator.py
- application/budget/serializers.py
- application/budget/tests/test_helpers.py
- application/budget/tests/tests.py
- application/budget/urls.py
- application/budget/views/money_distribution_views.py
Connects to Tiny-Hands/tinyhands-client#168
> Allow bulk exports for MDFs

- application/firebase/notification_builder.py
- application/firebase/notifications.py
-Topic now changed to general
-Messages now expire after 12 hours
-Messages have normal priority set
-iOS devices get badge on app icon now
-Created FirebaseNotificationBuilder to help simplify FCM message creation
No tests currently, they will be in different PR. Getting this out there for app testing
Connects to #354
> Expanding notification options

- Dockerfile
- application/bin/install_test_db.sh
- application/dataentry/views/interception_alert.py
* order alerts Descending
* make docker container start at /data when launched
* install site settings, redflags, and alerts on install_test_db.sh
> reversing the queryset so the newest alerts show up first

- application/firebase/management/commands/sendInterceptionAlertsNotification.py
> Removing "new" from Firebase notification

- docs/pull_request_template.md
This is adding a default template for pull requests. The main reason I want this in is so we don't forget to add the "Connects to" for linking to issues.
> Adding template for pull requests

- application/firebase/notifications.py
- Request data now UTF-8 encoded
Connects to #404
> Fixed firebase request error

- application/export_import/google_sheet_basic.py
> Update google_sheet_basic to force integer divide

- application/dataentry/tests/test_photo_exporter.py
- application/dataentry/views/photo_exporter.py
- application/rest_api/urls.py
Connects to #411
* Use BytesIO instead of StringIO since python 3 change
> zipfile uses bytes instead of strings in python 3

- application/dreamsuite/settings/base.py
Connects to #416 
* Switched server email to support email
> Switch server email to support@dreamsuite.org

- application/dataentry/management/commands/formLatest.py
Connects to #
* Missed new management command when branch was pushed to GitHub
*
*
> Management command formLatest was never added to branch

- application/dataentry/serialize_form.py
- application/dataentry/views/__init__.py
- application/dataentry/views/all_views.py
- application/dataentry/views/person.py
- application/rest_api/urls.py
and if found return the list of interceptee persons.
Update serialize_form to support a "link_id" value to be included when
person data is received.  The link_id is the ID of an existing person
record.  The new person record should be included in the same alias group as
the existing person record.
Connects to #
*
*
*
> Add endpoint to locate an IRF corresponsing to the form id supplied

- application/dreamsuite/settings/production.py
- build/deploy/run.sh
* Swap domain to searchlightdata.org
> Switch domain to searchlightdata

- application/dreamsuite/settings/production.py
- build/deploy/run.sh
Reverts Tiny-Hands/tinyhands#472
> Revert "Switch domain to searchlightdata"

- application/dataentry/migrations/0078_auto_20190212_0947.py
* Remove SQL query to see if it fixes migration
> Remove SQL query from migration 78

- application/dataentry/management/commands/migrateNepalCif.py
already a CIF with the same number (cif_number = vif_numberI).
In the previous version of the code, id values were assigned based on the
id of the corresponding VIF record.  With this version, the ids are
automatcally assigned the next available id value.
Connects to #
*
*
*
> Update command to create new CIFs for each existing VIF where the is not

- application/budget/views/budget_views.py
> Update budget view api to support filtering results by a set of country

- application/fixtures/initial-required-data/form_data.json
> Fix question type for location starting date (question 436).

- application/dataentry/views/photo_exporter.py
Also fix photo export when IRF has attachment cards
Connects to #512 
*
*
*
> Fix photo export to handle non-global permission

- .gitignore
> Add deploycfg to gitignore

- build/deploy/run.sh
Reverts Tiny-Hands/tinyhands#561
> Undo domain swap

- .gitignore
> Remove google map key file from git tracking

- build/deploy/run.sh
> Change URL

- build/nginx/server.conf.template
> Fix url for authorization for nginx

- application/export_import/photo_anonymizer.py
Connects to #
* Check if base image is none before anonymizing
> Check image before anonymizing

- application/export_import/photo_anonymizer.py
Connects to #
* Use try except instead of checking for non type
> Try except on image copying

- application/dreamsuite/settings/production.py
> Add 'web' to the list of allowed hosts.

- application/dataentry/alert_checkers.py
- application/dataentry/background_form_work.py
- application/dreamsuite/settings/production.py
- application/export_import/photo_anonymizer.py
> Put processing trafficker match and photo anonymizer in main thread

- application/dataentry/alert_checkers.py
Comment out Alert Checker for trafficker name match
> Disable trafficker match feature

- application/dataentry/serialize_form.py
- application/dataentry/views/cif_form.py
> Update CIF list to include main PVOT name and source of intelligence

- application/dataentry/views/indicators.py
- application/rest_api/urls.py
> Add endpoint to compute data collection indicators

- codeship-services.yml
> Attempt to fix codeship postgres issue

- build/nginx/server.conf.template
> Add locations for certbot test

- build/nginx/server.conf.template
> Reorder locations

- build/nginx/server.conf.template
> Remove certbot locations in conf

- application/export_import/export_form.py
- application/export_import/google_form_work_queue.py
- application/export_import/google_sheet_basic.py
> Fix issue with export when a spreadsheet is not present.

- build/nginx/server.conf.template
> attempt automatic certificates

- build/nginx/server.conf.template
> Back out changes for certbot

- application/dataentry/serializers.py
> Fix audit serializer divide by zero issue.

- application/dataentry/models/indicator_history.py
> Change storage cache name

- application/dataentry/models/indicator_history.py
- application/export_import/google_form_work_queue.py
> Fix indicators cache name

- application/fixtures/initial-required-data/form_data.json
The legal forced labor occured question.
Connects to #932 
*
*
*
> Corrected storage field name for question 405.

- application/dataentry/models/indicator_history.py
- application/fixtures/initial-required-data/form_data.json
> Fix CIF exploitation field name

- application/dataentry/views/statistics_dashboard.py
- application/fixtures/initial-required-data/form_data.json
> Fix LocationData duplicates

- application/fixtures/initial-required-data/form_data.json
> Add "first time traveling abroad" question to form data for Kenya IRF

- application/dataentry/views/statistics_dashboard.py
- application/fixtures/initial-required-data/form_data.json
> Kenya IRF Update

- application/dataentry/management/commands/oneFormPerPerson.py
associated with a person.
Connects to #942 
*
*
*
> Add Management command to fix cases where more than one form is

- application/dataentry/views/indicators.py
> Fix data collection CIF % calculation.

- application/dataentry/management/commands/sanitizePrivate.py
> Update sanitizePrivate to include legal case models.

- application/dataentry/serializers.py
> Update permission serializer for permission granting algorithm.

- application/budget/views/budget_views.py
Connects to #
* Hotfix for staff_items
*
*
> Fixed initialization of staff_items array when creating new budget.

- build/nginx/server.conf.template
Connects to #992 
*
*
*
Note that installing this change will continue to use the previous certificate.  Manual actions are required on the server to enable the initial new certificates and to enable the renewal.
> Attempt to use certbot

- application/dataentry/management/commands/populateStationStatistics.py
- application/dataentry/views/statistics_dashboard.py
- application/rest_api/urls.py
> Populate arrests and convictions from legal cases

- application/dataentry/views/statistics_dashboard.py
- application/static_border_stations/views.py
> Station Statistics/Station updates

- application/dataentry/management/commands/populateStationStatistics.py
- application/dataentry/views/statistics_dashboard.py
- application/rest_api/urls.py
Reverts Tiny-Hands/tinyhands#991
> Revert "Populate arrests and convictions from legal cases"

- application/dataentry/views/statistics_dashboard.py
> Include non-monitoring locations in location data/staff

- application/dataentry/views/statistics_dashboard.py
> Fix setting arrests to blank on station data

- application/dataentry/management/commands/exportStationStats.py
> Include exchange rate in export of station stats

- application/fixtures/initial-required-data/form_data.json
> Hotfix for VDF 4.3 options

- application/dataentry/views/vdf_form.py
> Add order to VDF view

- application/dataentry/views/vdf_form.py
- application/fixtures/initial-required-data/form_data.json
> Add order to VDF list

- build/nginx/server.conf.template
- codeship-steps.yml
Add operations management routes to nginx on the server.
> Ops man nginx routes

- application/dataentry/views/audit.py
- application/dataentry/views/indicators.py
> Update calculation of station compliance score

- build/nginx/server.conf.template
> Remove ops-man routes

- build/nginx/server.conf.template
> Increase configuration to set upload size limit to 100M

- application/dataentry/views/master_person.py
- application/dreamsuite/settings/base.py
> Add match results to history

- application/dataentry/serialize_form.py
> Hotfix for stations concurrency issue.

- application/dataentry/serialize_form.py
> Hotfix for concurrency with stations

- application/dataentry/models/person.py
When finding alias names
Connects to #1187 
*
*
*
> Add check for null name in person

- application/dataentry/management/commands/populateStationStatistics.py
> Reset intercepts in location statistics for inactive locations

- application/dataentry/views/statistics_dashboard.py
> dashboard 6 month code incorrectly indented

- application/dataentry/management/commands/populateStationStatistics.py
> Avoid overwritting exchange rate

- application/dataentry/management/commands/populateStationStatistics.py
- application/dataentry/views/statistics_dashboard.py
> Stop budget population in populateStatistics

- application/dataentry/views/statistics_dashboard.py
> project statistics dashboard include to date emp

- application/budget/models.py
> Use other_project_items for PV extra items

- application/budget/models.py
> Add rent and utilities to project total

- application/budget/models.py
> Add Rent & Utilities to Project Total

- application/dataentry/views/statistics_dashboard.py
> Fix update of project work days

- application/dataentry/views/irf_form.py
Kept IRF notifications from being sent due to exception
Connects to #1259 
*
*
*
> Fix issue with datetime import

- application/dataentry/serializers.py
- application/dataentry/views/irf_form.py
> Fix divide by zero for station data

- application/budget/migrations/0006_auto_20210615_1743.py
- application/budget/migrations/0011_auto_20220406_1216.py
> Missing space in migration sql

- application/templates/templated_email/suggested_match.email
> Add missing email template for id matching.

- application/fixtures/initial-required-data/form_data.json
> Restore form data for Nepal SFE IRF

- application/fixtures/initial-required-data/form_data.json
> Fix form data form IRF SFE how agent contacted

- application/dataentry/views/indicators.py
> Collection indicator updates

- application/dataentry/views/statistics_dashboard.py
> Update sort when computing dashboard values

- .github/workflows/build_test_deploy.yml
- Dockerfile
- build-containers.sh
- build/base/build-and-push-image.sh
- build/cron/Dockerfile
- codeship-services.yml
- codeship-steps.yml
- push-containers.sh
> Update deploy process with GitHub Action

- .github/workflows/build_test_deploy.yml
> Use private key variable for scp and ssh

- .github/workflows/build_test_deploy.yml
> Use ssh_key file name

- application/dataentry/views/person.py
> Fix alert when opening PVF

- application/dataentry/views/forms.py
> Include underscore when getting base number for related forms search

- application/dataentry/views/indicators.py
> Data collection indicators fix not present logic

- build/nginx/server.conf.template
File already uses 'listen 443 default_server ssl;' so it should be fine
> Remove 'ssl on' command

- application/fixtures/initial-required-data/form_data.json
> Gospel required fields & Ethiopia new question

- application/budget/models.py
> Typo for multiplier

- application/export_import/form_data_tag_serializer.py
- application/fixtures/initial-required-data/form_data.json
- application/fixtures/initial-required-data/form_data_SF.json
Update form data load and dump to handle validation for tag based forms.
Connects to #
*
*
*
> Add missing question to SFE IRF.  Add SF validation

- application/dataentry/models/irf_common.py
- application/dataentry/serialize_form.py
- application/dataentry/views/base_form.py
- application/export_import/form_data_tag_serializer.py
- application/fixtures/initial-required-data/form_data.json
- application/fixtures/initial-required-data/form_data_LF.json
- application/fixtures/initial-required-data/form_data_PVF.json
- application/fixtures/initial-required-data/form_data_SF.json
> Fix est. birthdate / New forms final countries

- application/dataentry/migrations/0258_auto_20230509_1844.py
> Change dataentry migration for project requests

- application/budget/migrations/0014_auto_20230628_1454.py
> Make change for budget migration

- application/dataentry/views/photo_exporter.py
> Use 'verified' status for photo export

- application/dataentry/management/commands/removeUnrefPerson.py
> Add management command to remove unreferenced persons

- application/static_border_stations/views.py
> Fix search by project name/project code

- application/budget/models.py
- application/budget/views/monthly_distribution_form_views.py
- application/export_import/mdf_io.py
> Export MDF data to Google sheet

- application/dataentry/validate_form.py
- application/fixtures/initial-required-data/form_data.json
- application/fixtures/initial-required-data/form_data_LF.json
- application/fixtures/initial-required-data/form_data_PVF.json
- application/fixtures/initial-required-data/form_data_SF.json
> Make date form received required

- application/budget/views/money_distribution_views.py
- application/templates/templated_email/money_distribution_form.email
> Fix MDF email to work with both old and new versions of MDF

- application/rest_api/urls.py
> re-add monitor-form endpoint into urls.py

- application/fixtures/initial-required-data/Permission.json
- application/static_border_stations/tests/factories.py
- application/static_border_stations/tests/test_staff_api.py
- application/static_border_stations/views.py
> Fix endpoint to return staff list for a project

- application/dataentry/views/forms.py
- application/dataentry/views/photo_exporter.py
- application/export_import/export_form_csv.py
- application/rest_api/urls.py
> allow export of IRF & PVF to csv file

- application/budget/urls.py
- application/budget/views/monthly_distribution_form_views.py
- application/budget/views/project_request.py
- application/templates/templated_email/discussion_notify.email
> Allow filter PBS by status

- application/dataentry/views/statistics_dashboard.py
> Fix location staff total when work_fraction is null

- application/budget/views/project_request.py
Connects to #
* Fix error if there is no pending MDF and you are changing the amount on an existing recurring request
> Check for pending_mdf_list before trying to access first element

- application/legal/migrations/0001_initial.py
> Handle case where legal case suspect name is null

- application/static_border_stations/serializers.py
> Include has_pbs in StaffSerializer

- application/dataentry/views/forms.py
> Fix exception getting form versions for audit.

- application/fixtures/initial-required-data/form_data_LEGAL_CASE.json
- application/static_border_stations/serializers.py
- application/static_border_stations/views.py
> Miscellaneous updates Legal Cases, IRF, Subcommittee

- application/legal/serializers.py
> Update serializer to return last timeline event for legal case list

- application/static_border_stations/migrations/0009_staff_photo.py
> Change staff photo dependency

- application/static_border_stations/serializers.py
- application/static_border_stations/views.py
> Create and save blank staff object

- application/budget/management/commands/pbsExport.py
- application/export_import/mdf_io.py
> Update PBS export & add pbsExport management command

- application/dataentry/views/gospel.py
> Gospel mini-form search and sort on name

- application/fixtures/initial-required-data/form_data.json
- application/fixtures/initial-required-data/form_data_PVF.json
> Add Philippines IRF form data / Fix PVF 6.7

- application/dataentry/views/indicators.py
> Data Collection Indicators: SF/LF associated intercepts

- application/templates/templated_email/verification_notice.email
- application/templates/templated_email/verification_tie_notice.email
- application/templates/templated_email/verification_tie_resolved.email
> Verification email text edits

- application/budget/models.py
> Update guide computation

- application/dataentry/validate_form.py
> Submission Date Validation not Triggering

- application/budget/models.py
> Fix MDF project total

- application/dreamsuite/settings/base.py
> Include email variables in base.py

- build/nginx/server.conf.template
> Update nginx for react client file access

- build/nginx/server.conf.template
> Change quote character

- application/dataentry/serialize_form.py
- application/fixtures/initial-required-data/form_data.json
> LOVE-196 Better form tags for older forms

- application/dataentry/serialize_form.py
> Form deserializer remove reliance on question id

- application/budget/templates/budget/MoneyDistributionProjectRequestTemplate.rml
> LOVE-185 Add signature line and spending guidelines

- application/budget/helpers.py
- application/budget/migrations/0017_monthlydistributionform_money_not_spent_reviewed_and_more.py
- application/budget/migrations/0018_stationary_to_stationery.py
- application/budget/models.py
> LOVE-184 Change stationary to stationery

- application/export_import/export_form_csv.py
> LOVE-198 PVF follow-up pull - prioritize contact information

- application/export_import/mdf_io.py
> LOVE-206 Include deductions in MDF export

- application/budget/helpers_pr.py
> MDF helper did not exclude declined project request

- application/export_import/export_form_csv.py
Change date filter for IRF to be by verification date
Connects to #
*
*
*
> export form: change location to non-private

- .github/workflows/build_test_deploy.yml
> Install docker-compose for GitHub action

- application/dataentry/views/base_form.py
LOVE-219 - Just skipping over the log for projects since form_number is a not null requirement and we don't really need to log project changes
Connects to #
*
*
*
> Form log erroring on Project updates

- application/fixtures/initial-required-data/form_data_LEGAL_CASE.json
> Fix warnings when suspect not arrested

- application/dataentry/serializers.py
> Include country_id in emp serializer

- application/accounts/management/commands/create_users_with_password_hashes_in_auth0.py
- application/util/auth0.py
LOVE-203
To run in production, requires the env variable AUTH0_DATABASE_CONNECTION_ID that Brad has locally
> Add command that creates Django users in Auth0

- application/dataentry/models/vdf_common.py
- application/dataentry/views/base_form.py
Add code to handle form number with None value
Connects to #
*
*
*
> Fix form_log: Add get_key for GospelVerification model

- application/fixtures/initial-required-data/form_data_PVF.json
> Remove duplicate questionLayout for PVF so new UI works correctly

- application/budget/views/monthly_distribution_form_views.py
Connects to #
* Current MDF submission permission is tied to review rather than ADD
> MDF Initial Submission Permission

- application/legal/management/commands/importLegalCharge.py
> LOVE-214 Import Legal Cases from Spreadsheet

- application/dataentry/serialize_form.py
- application/dataentry/views/sf_form.py
> Fix SF Form  blank form creation

- application/static_border_stations/views.py
> Sort staff by both first and last names

- application/dataentry/models/border_station.py
- application/dataentry/models/monthly_report.py
- application/dataentry/serialize_form.py
Add incident_id and incident_number to serializer for most forms
> Add incident id to serializer

- application/dataentry/tests/factories.py
- application/dataentry/validate_form.py
> Fix validation based on submission date

- application/dataentry/views/auth0.py
- application/rest_api/urls.py
> Add password reset link

- application/legal/management/commands/importLegalCharge.py
> Return new PVF object after creating

- application/fixtures/initial-required-data/form_data.json
- docker-compose.yml
> Form data updates for India Network and Narrative validation

- application/legal/models/legal.py
> Return None for key when incident_id is None

- application/dataentry/views/auth0.py
- application/rest_api/urls.py
- application/util/auth0.py
Copied this code from the Operations Management project. It allows you to hit an endpoint with Postman (PATCH request) with an auth0 id and it creates (or updates if they already exist) an account in Django for them.
> Feature/create account from auth0 LOVE-286

- application/static_border_stations/serializers.py
> Send contract_expiration date rather than date added

- application/budget/helpers_pr.py
> LOVE-280 PBS - Allow multiple deductions

- common.env
(github secrets for react and backend env files also need to be updated)
> Change auth0 login domain

- README.md
> Add more commands

- application/legal/serializers.py
- application/legal/views/legal_charge_form.py
Include incident date and number of verified arrests
Connects to #
*
*
*
> LOVE-253 update legal case list

- README.md
- application/dreamsuite/settings/base.py
- application/dreamsuite/urls.py
> Attachments to Azure part 2

- application/dreamsuite/settings/base.py
- application/dreamsuite/urls.py
> Revert azure storage

- application/dreamsuite/settings/base.py
- application/dreamsuite/urls.py
Reverts LoveJustice/tinyhands#1643
> Revert "Revert azure storage"

- application/budget/views/monthly_distribution_form_views.py
Previous month values for the project trends had the same issue
Connects to #
*
*
*
> Fix PBS national review to filter out Approved-Completed

- application/budget/models.py
> Don't include deductions that were completed in PBS export

- README.md
- common_sql/fix_bad_pvf_migration.sql
My PR of shame for not checking if everything had been deployed.
> fix(formMigration): Add SQL query for bad PVF migration

- application/budget/views/monthly_distribution_form_views.py
Sorry it included some formatting cleanup too
> LJ-559: Exclude declined requests from totals
